### PR TITLE
updates to middleman 4.2 and fixes tests

### PR DESCRIPTION
**Pull request by hwhelchel**
@plasticine I didn't add any tests but just updated the code to get the tests to pass. Can you take a look at this when you have a chance?

### CODE REVIEW

**Comment by plasticine** [comment]
@hwhelchel Hey there—thanks for this! It looks great. Are the tests passing for you locally, or is it just CI?

**Comment by hwhelchel** [comment]
I took a look at the CI build. Since you rightly aren't checking in the
lock file the new dependencies aren't being updated for some reason. Not
sure if it's a fix on my end or in your CI build script.

On Thursday, June 23, 2016, Justin Morris <notifications@github.com> wrote:

> @hwhelchel <https://github.com/hwhelchel> Hey there—thanks for this! It
> looks great. Are the tests passing for you locally, or is it just CI?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/plasticine/middleman-imageoptim/pull/48#issuecomment-228191243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEkgN2hOwAB8pr90cw3w6rHKUABWsVXvks5qOvvdgaJpZM4I9PQt>
> .
>


-- 
Harry

**Comment by hwhelchel** [comment]
All tests pass locally


On Thursday, June 23, 2016, Justin Morris <notifications@github.com> wrote:

> @hwhelchel <https://github.com/hwhelchel> Hey there—thanks for this! It
> looks great. Are the tests passing for you locally, or is it just CI?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/plasticine/middleman-imageoptim/pull/48#issuecomment-228191243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEkgN2hOwAB8pr90cw3w6rHKUABWsVXvks5qOvvdgaJpZM4I9PQt>
> .
>


-- 
Harry

**Comment by plasticine** [comment]
@hwhelchel OK, thanks. I’ll investigate what’s going on with CI.

**Comment by tisba** [comment]
<3 for making imageoptim work with middleman v4 again! This branch seems to work fine for us. Any chance to get the CI issue figured out and this PR merged?

**Comment by lifeiscontent** [comment]
@plasticine +1

**Comment by pusewicz** [comment]
*bump*

**Comment by chenware** [comment]
+1

**Comment by TheE** [comment]
Any news?

**Comment by conraddecker** [comment]
❤️  @hwhelchel Thank you for giving this a push! @plasticine Is there anything we can do to help? I'm admittedly a little bit out of my league here but I'd be more than happy to dig in if there's some direction you can point me in?

**Comment by chrishough** [comment]
+1

**Comment by hwhelchel** [comment]
@plasticine I got the build to pass. Notable changes:

Switched appraisals to 4.0, 4.1, and 4.2 versions of middleman.
Changed travis build matrix to run against ruby 2.2.6 and 2.3.3.

I made my changes backward compatible with middleman < 4.0.0. Not sure if that is necessary.

**Comment by chrishough** [comment]
Awesome @hwhelchel

**Comment by plasticine** [comment]
@hwhelchel Awesome—thanks very much <3 Will get this released.

**Comment by manuelmeurer** [comment]
Could you release a new gem version please?

**Pull request merged**
